eureka:
  instance:
    hostname: localhost
    ip-address: 192.168.1.100
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
name:
  value: alibou
spring:
  cloud:
    config:
      override-system-properties: false